---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "remove unused dependencies"
  become: yes
  apt: 
    autoremove: yes
- name: "Install dependencies"
  become: yes
  apt: 
    name: ['unzip', 'tar']
    state: latest
    update_cache: yes
- name: Create directory
  file: 
    path: ~/app
    state: directory

- name: Unzip dist directory
  ansible.builtin.unarchive:
    src: "dist.zip"
    dest: "~/app"
- name: "Executing nodejs"
  shell: |
    cd ~/app
    rm -rf dist.zip
    pm2 start main.js -f