---

- name: Create directory
  file: 
    path: ~/app
    state: directory
- name: Copy zipped dist
  copy:
    src: "dist.zip"
    dest: "~/app/dist.zip"
- name: Unzip dist directory
  shell: |
    cd ~/app
    tar xzvf dist.tar.gz
    # unzip dist.zip
- name: "Executing nodejs"
  shell: |
    pm2 start ~/app/main.js -f