---

- name: Create directory
  file: 
    path: ~/app
    state: directory
# - name: Copy zipped dist
#   copy:
#     src: "dist.zip"
#     dest: "~/app/dist.zip"
- name: Unzip dist directory
  ansible.builtin.unarchive:
    src: "dist.zip"
    dest: "~/app"

- name: "Executing nodejs"
  shell: |
    pm2 start ~/app/main.js -f