---

- name: Create directory
  file: 
    path: ~/app
    state: directory
- name: "Install dependencies"
  become: yes
  apt: 
    name: ['unzip', 'tar']
    state: latest
    update_cache: yes
- name: Unzip dist directory
  ansible.builtin.unarchive:
    src: "dist.zip"
    dest: "~/app"
- name: "Executing nodejs"
  shell: |
    pm2 start ~/app/main.js -f